require "yaml"
require "json"
require_relative "kwalify_to_json_schema/kwalify_to_json_schema"
require_relative "kwalify_to_json_schema/serialization"
require_relative "kwalify_to_json_schema/converter"
